(()=>{'use strict';
const RELEASE='production-20260911-v4',root=new URL('./',document.currentScript.src),form=document.querySelector('#unlock'),status=document.querySelector('#status'),button=document.querySelector('#enter'),deviceSelect=document.querySelector('#device'),frame=document.querySelector('#game'),gate=document.querySelector('#gate'),authKey='maitha-tab-auth-v4';
const touch=navigator.maxTouchPoints>0||matchMedia('(pointer:coarse)').matches;
deviceSelect.value=touch?(/iPad/.test(navigator.userAgent)||Math.min(screen.width,screen.height)>=600?'ipad':'iphone'):'desktop';
try{const v=localStorage.getItem('maitha-device-profile');if(['iphone','ipad','desktop'].includes(v))deviceSelect.value=v;}catch{}
const route=new URL(location.href);if(/iphone|ipad/.test(route.hash)){route.searchParams.set('device',route.hash.includes('iphone')?'iphone':'ipad');route.hash='';history.replaceState(null,'',route);}const requested=route.searchParams.get('device');if(location.hostname.endsWith('github.io')){route.pathname=root.pathname;route.hash='';for(const k of [...route.searchParams.keys()])if(!['device','v','qa'].includes(k))route.searchParams.delete(k);history.replaceState(null,'',route);}if(['iphone','ipad','desktop'].includes(requested))deviceSelect.value=requested;
deviceSelect.onchange=()=>{try{localStorage.setItem('maitha-device-profile',deviceSelect.value);}catch{}};
let key,manifest,urls=[],modules=new Map(),generation=0,watchdog;
const log=[];window.maithaLoadLog=log;function note(stage,detail=''){log.push({stage,detail,time:Date.now()});status.textContent=detail||stage;}
const decode=b=>new TextDecoder().decode(b),nativeFetch=window.fetch.bind(window);
async function request(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const r=await nativeFetch(new URL(url,root),{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error('HTTP '+r.status+' '+url);return new Uint8Array(await r.arrayBuffer());}finally{clearTimeout(timer);}}
async function loadManifest(){if(!manifest)manifest=JSON.parse(decode(await request('manifests/'+RELEASE+'.json')));return manifest;}
async function decryptFile(name){const m=await loadManifest(),file=m.files[name];if(!file)throw Error('Missing file '+name);let sealed;if(file.parts){sealed=new Uint8Array(file.sealedBytes);for(const part of file.parts){const bytes=await request(part.path);if(bytes.length!==part.bytes)throw Error('Incomplete '+name);sealed.set(bytes,part.offset);}}else sealed=await request(file.path);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:sealed.subarray(0,12)},key,sealed.subarray(12));return new Response(plain,{headers:{'Content-Type':file.type,'Content-Length':String(plain.byteLength)}});}
function assetName(value){const url=new URL(value,new URL('play/',root));if(url.origin!==root.origin||!url.pathname.startsWith(root.pathname+'play/'))return null;return decodeURIComponent(url.pathname.slice((root.pathname+'play/').length));}
function blob(text,type){const url=URL.createObjectURL(new Blob([text],{type}));urls.push(url);return url;}
function moduleURL(name,chain=[]){if(chain.includes(name))throw Error('Module cycle '+name);if(modules.has(name))return modules.get(name);const work=(async()=>{let source=await(await decryptFile(name)).text();const matches=[...source.matchAll(/(?:\bfrom\s*|\bimport\s*)['"](\.[^'"]+\.js)['"]/g)];const replacements=await Promise.all(matches.map(async match=>{const dependency=new URL(match[1],new URL('play/'+name,root));return[match[1],await moduleURL(assetName(dependency.href),[...chain,name])];}));for(const [relative,url]of replacements)source=source.split("'"+relative+"'").join("'"+url+"'").split('"'+relative+'"').join('"'+url+'"');return blob(source,'text/javascript');})();modules.set(name,work);return work;}
function teardown(){generation++;clearTimeout(watchdog);try{frame.contentWindow?.maithaShutdown?.();}catch{}frame.removeAttribute('src');frame.srcdoc='';frame.hidden=true;for(const url of urls)URL.revokeObjectURL(url);urls=[];modules.clear();}
function failed(error){clearTimeout(watchdog);console.error('Maitha startup failed',error);note('error','تعذّر فتح اللعبة: '+error.message+' — اضغطي دخول للمحاولة مرة ثانية.');teardown();gate.hidden=false;button.disabled=false;document.querySelector('#logout').hidden=!key;}
async function mount(){teardown();const token=generation;gate.hidden=false;button.disabled=true;note('modules','نفتح اللعبة ونجهّز ملفاتها…');const [html,css,main]=await Promise.all([decryptFile('index.html').then(r=>r.text()),decryptFile('style.css').then(r=>r.text()),moduleURL('main.js')]);if(token!==generation)return;
 const config={generation:token,device:deviceSelect.value,qa:new URL(location.href).searchParams.has('qa')};
 window.maithaHost={fetch:async(input,init)=>{const name=assetName(typeof input==='string'?input:input.url);if(name)return decryptFile(name);return nativeFetch(input,init);},ready:id=>{if(id!==token||token!==generation)return;clearTimeout(watchdog);note('ready','اللعبة جاهزة');gate.hidden=true;frame.hidden=false;frame.style.visibility='';document.querySelector('#logout').hidden=false;},error:(message,id)=>{if(id===token&&token===generation)failed(Error(message));},reload:device=>{if(device)deviceSelect.value=device;mount().catch(failed);},importModule:async name=>import(await moduleURL(name))};
 const bootstrap=`<script>window.MAITHA_BOOT=${JSON.stringify(config)};const realFetch=window.fetch.bind(window);window.fetch=(input,init)=>{const u=new URL(typeof input==='string'?input:input.url,document.baseURI);return u.origin===parent.location.origin&&u.pathname.startsWith(${JSON.stringify(root.pathname+'play/')} )?parent.maithaHost.fetch(u.href,init):realFetch(input,init);};window.addEventListener('error',e=>parent.maithaHost.error(e.message||'تعذّر تحميل ملف اللعبة',window.MAITHA_BOOT.generation));<\/script>`;
 const content=html.replace('<head>','<head><base href="'+new URL('play/',root).href+'">').replace('<link rel="stylesheet" href="style.css">','<style>'+css+'</style>').replace('<script type="module" src="main.js"></script>',bootstrap+'<script type="module" src="'+main+'"></script>');
 frame.hidden=false;frame.style.visibility='hidden';frame.srcdoc=content;note('render','نحمّل الشخصيات… تبقى هذه الشاشة حتى تجهز اللعبة.');watchdog=setTimeout(()=>failed(Error('انتهت مهلة تحميل الشخصيات؛ تأكدي من الاتصال وأعيدي المحاولة')),90000);
}
async function verify(candidate){const m=await loadManifest(),b=await request(m.verify);await crypto.subtle.decrypt({name:'AES-GCM',iv:b.subarray(0,12)},candidate,b.subarray(12));key=candidate;document.querySelector('#password').required=false;}
form.addEventListener('submit',async e=>{e.preventDefault();button.disabled=true;note('unlock','نتحقق من كلمة المرور…');try{if(!isSecureContext||!crypto.subtle)throw Error('استخدمي Safari أو متصفحًا حديثًا');if(!key){const m=await loadManifest(),base=await crypto.subtle.importKey('raw',new TextEncoder().encode(document.querySelector('#password').value),'PBKDF2',false,['deriveBits']),raw=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:Uint8Array.from(atob(m.salt),c=>c.charCodeAt(0)),iterations:m.iterations},base,256),candidate=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['decrypt']);await verify(candidate);try{sessionStorage.setItem(authKey,JSON.stringify({v:4,key:btoa(String.fromCharCode(...new Uint8Array(raw))),at:Date.now()}));}catch{}document.querySelector('#password').value='';}await mount();}catch(e){if(e.name==='OperationError'){key=null;status.textContent='كلمة المرور غير صحيحة، جرّبي مرة ثانية.';button.disabled=false;}else failed(e);}});
document.querySelector('#logout').onclick=()=>{teardown();key=null;document.querySelector('#password').required=true;try{sessionStorage.removeItem(authKey);}catch{}gate.hidden=false;button.disabled=false;document.querySelector('#logout').hidden=true;note('logout','تم الخروج. تقدم اللعبة محفوظ على هذا الجهاز.');};
// Retire only this game's old worker; startup never waits for a worker.
try{navigator.serviceWorker?.getRegistrations().then(all=>Promise.all(all.filter(r=>r.scope===root.href).map(r=>r.unregister()))).catch(()=>{});}catch{}
// No service worker or cross-frame key transfer participates in this launch path.
(async()=>{try{const r=JSON.parse(sessionStorage.getItem(authKey)||'null');if(!r||r.v!==4||!Number.isFinite(r.at)||r.at>Date.now()||Date.now()-r.at>12*3600000)return;button.disabled=true;note('restore','نسترجع جلستك…');await verify(await crypto.subtle.importKey('raw',Uint8Array.from(atob(r.key),c=>c.charCodeAt(0)),{name:'AES-GCM'},false,['decrypt']));await mount();}catch(e){key=null;try{sessionStorage.removeItem(authKey);}catch{}failed(e);}})();
})();
