'use strict';
const root=new URL('./',self.location.href),keyCache=new Map(),manifests=new Map();
self.addEventListener('install',e=>e.waitUntil(self.skipWaiting()));self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));
async function manifest(event){let version=new URL(event.request.url).searchParams.get('release');if(!version&&event.clientId){const client=await self.clients.get(event.clientId);if(client)version=new URL(client.url).searchParams.get('release');}if(version&&!/^[a-zA-Z0-9-]+$/.test(version))throw Error('Invalid release');const id=version||'current';if(!manifests.has(id)){const pending=fetch(new URL(version?'manifests/'+version+'.json':'manifest.json',root),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('manifest');return r.json();}).catch(e=>{manifests.delete(id);throw e;});manifests.set(id,pending);}return manifests.get(id);}
async function keyFor(event){let session=new URL(event.request.url).searchParams.get('session');if(!session&&event.clientId){const client=await self.clients.get(event.clientId);if(client)session=new URL(client.url).searchParams.get('session');}if(!session)return null;if(keyCache.has(session))return keyCache.get(session);
 const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});const candidates=clients.filter(c=>{const u=new URL(c.url);return u.origin===root.origin&&(u.pathname===root.pathname||u.pathname===root.pathname+'index.html');});
 const keys=await Promise.all(candidates.map(c=>new Promise(resolve=>{const ch=new MessageChannel(),timer=setTimeout(()=>{ch.port1.close();resolve(null);},2000);ch.port1.onmessage=e=>{clearTimeout(timer);ch.port1.close();resolve(e.data);};c.postMessage({type:'maitha-key',session},[ch.port2]);})));const key=keys.find(Boolean);if(key){keyCache.set(session,key);if(keyCache.size>8)keyCache.delete(keyCache.keys().next().value);}return key;
}
self.addEventListener('fetch',event=>{const url=new URL(event.request.url),prefix=root.pathname+'play/';if(url.origin!==root.origin||!url.pathname.startsWith(prefix))return;
 event.respondWith((async()=>{try{const name=decodeURIComponent(url.pathname.slice(prefix.length)),m=await manifest(event),file=m.files[name];if(!file)return new Response('Not found',{status:404});const key=await keyFor(event);if(!key){if(event.request.mode==='navigate')return Response.redirect(root.href,302);return new Response('Enter the kingdom password first.',{status:401,headers:{'Cache-Control':'no-store'}});}const sealed=await readSealed(file),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:sealed.subarray(0,12)},key,sealed.subarray(12));return new Response(plain,{headers:{'Content-Type':file.type,'Content-Length':String(plain.byteLength),'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}catch(error){console.error('Kingdom file could not load',url.pathname,error.message);return new Response('Loading failed. Refresh the kingdom and try again.',{status:503});}})());
});

async function readSealed(file){if(!file.parts){const r=await fetch(new URL(file.path,root));if(!r.ok)throw Error('asset '+r.status);return new Uint8Array(await r.arrayBuffer());}const bytes=new Uint8Array(file.sealedBytes);for(let i=0;i<file.parts.length;i+=3)await Promise.all(file.parts.slice(i,i+3).map(async part=>{const r=await fetch(new URL(part.path,root));if(!r.ok)throw Error('part '+r.status);const b=new Uint8Array(await r.arrayBuffer());if(b.length!==part.bytes)throw Error('part size');bytes.set(b,part.offset);}));return bytes;}
